name: Upload Website #Se crea un nuevo flujo de trabajo llamado Upload Website

#Este va a correr cada vez que invoquemos el evento 
# push a la rama llamada main 
on:
  push:
    branches:
      - main

#va a correr dentro de una maquina virtual de linux utilizando
# la distribucion ubuntu, y dentro de esta maquina virtual se 
# ejecutan los siguientes pasos:
# va a verificar el repositorio (actions/checkout@master)
# va a intalar dependencias (npm install)
# va a generar una version de produccion (npm run build)
# Se comunica el repositorio en gitHub con el bucke en amazon s3  
# se especifica la configuracion (--acl public-read --follow-symlinks --delete)    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - run: npm install
      - run: CI='' npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env: 
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'build'

